spring.application.name=ApiDZ

spring.datasource.url=jdbc:h2:mem:maindb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=embedded

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource-rules.url=jdbc:postgresql://localhost:5432/rules_db
spring.datasource-rules.driver-class-name=org.postgresql.Driver
spring.datasource-rules.username=postgres
spring.datasource-rules.password=Admin

spring.liquibase.change-log=classpath:db/changelog/db/changelog-master.yaml

cache.caffeine.spec=maximumSize=500,expireAfterWrite=15m

telegram.bot.username=bbislv
telegram.bot.token=8726606813:AAGWbvPqjnhm0S3Rx73wCVnpj_qIUtl6RqM

management.service.name=ApiDZ

logging.level.com.example.ApiDZ.bot=INFO
logging.level.com.example.ApiDZ.config.TelegramBotConfig=INFO